### ISSUE TITLE
Old table references are not removed

### ISSUE THREAD

**Issue by JoJones80** [untermensch/WindSLIC#2]
WindSLIC UEFI doesn't check for or attempt to update existing SLIC or MSDM tables. That's a problem because you can end up with 2 SLIC tables and 2 MSDM tables and Windows won't always use the correct one.

I'm wanting to use WindSLIC to update my current SLIC to version 2.3 so that I can activate Windows Server 2012 R2. Any help? Thanks.

**Comment by AR1972** [comment]
All the code to do this was already written and tested and is present in the WindSLIC code base, I have just never gotten around to implementing it. I will try to have it implemented by this weekend.

**Comment by untermensch** [comment]
I pushed the code to produce the expected behavior, I have not had time to test.

**Comment by JoJones80** [comment]
Awesome! I'm looking forward to testing it. Thanks again.

**Comment by AR1972** [comment]
I just pushed the changes.
